spring:
  application:
    name: board-client

  security:
    oauth2:
      client:
        provider:
          local-authorization-server:
            issuer-uri: http://localhost:8080

        registration:
          board-client:
            provider: local-authorization-server
            client-id: board-client
            client-secret: secret
            client-authentication-method: client_secret_basic
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope:
              - openid
              - profile
              - read
            client-name: 게시판 클라이언트

      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080

server:
  port: 8081
  servlet:
    session:
      cookie:
        name: JSESSIONBOARDID
